### ISSUE TITLE
Text syntax for array type definition

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wasp#55]
The follow code for an array definition:
```
(module
  (type $bytes (array (mut i8)))
)
```
produce the follow error:
```
test.wat:2:23: Expected '(' Field, got Lpar Mut
  (type $bytes (array (mut i8)))
                      ^
test.wat:2:23: Expected Rpar, got Lpar
  (type $bytes (array (mut i8)))
                      ^
test.wat:2:23: Expected Eof, got Lpar
  (type $bytes (array (mut i8)))
                      ^
```

With a `field` expression which is unexpected for arrays it will work:
```
(module
  (type $bytes (array (field (mut i8))))
)
```
see also: https://github.com/WebAssembly/gc/issues/172

PS: The error message also suggest an uppercase `Field` but it must be a lowercase `field`.

**Comment by jDramaix** [comment]
Hi any idea when this fix will be submitted ?

**Comment by binji** [comment]
Sorry, landed!
